field: c4fb0464-3077-45aa-9c64-7e0015f54677 # Alert Bar
fieldLayouts:
  8c8ced71-5350-44b0-b38c-0d570dde703d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 17c63dc5-a8a5-4077-84e6-6f5d5baa1e46 # Start Date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ed88d6a-2e36-4fbb-8c70-363482a71128
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5afb69df-76c7-42e3-9af4-bc31faefa3d5 # End Date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01edc326-d60d-4208-ad74-544e7e2ba829
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60b2f9cd-8e83-49e0-921e-f6d0b325e69d # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fc773dd-ab18-4abb-b268-c93a8ab01e9c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3c098591-b8b9-4bab-b64d-09659b251c76
        userCondition: null
fields:
  5afb69df-76c7-42e3-9af4-bc31faefa3d5: # End Date
    columnSuffix: null
    contentColumnType: datetime
    fieldGroup: null
    handle: endDate
    instructions: 'When the alert should stop showing'
    name: 'End Date'
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: 60
      showDate: true
      showTime: true
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  17c63dc5-a8a5-4077-84e6-6f5d5baa1e46: # Start Date
    columnSuffix: null
    contentColumnType: datetime
    fieldGroup: null
    handle: startDate
    instructions: 'When the alert should start showing'
    name: 'Start Date'
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: 60
      showDate: true
      showTime: true
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  60b2f9cd-8e83-49e0-921e-f6d0b325e69d: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'The text of the alert bar'
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: alert
name: Alert
sortOrder: 1
