field: 0f821582-b0f9-4517-9422-53b6ce1325ac # Content Matrix
fieldLayouts:
  1525beae-1aa5-4f28-8e58-76fac2482471:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 04d471b6-495e-4558-b583-c7c366635c98 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44b127c2-42f2-40ec-9f23-8219ed214d34
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1edd02fb-b01b-4fc9-90fb-0b111094ab5f # Form
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed0f1f68-a013-4497-bf6c-267b5bdbcebf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f6d65961-c80a-4896-972d-9ec8dd995341
        userCondition: null
fields:
  1edd02fb-b01b-4fc9-90fb-0b111094ab5f: # Form
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: 'Select a form to include on the page. Forms can be created and edited from the **Freeform** option in the sidebar on the left.'
    name: Form
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
  04d471b6-495e-4558-b583-c7c366635c98: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Appears above the form'
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 3c62ae9b-e6d3-4100-a0d1-1c5abab96be2 # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: form
name: Form
sortOrder: 1
