field: 0f821582-b0f9-4517-9422-53b6ce1325ac # Content Matrix
fieldLayouts:
  6b8a5bf3-93ba-4dcc-a120-cfbd5079af8a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 63092641-8191-4272-9d2b-870c0e7aa674 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0eec332a-8470-4fe0-8cd2-51eb90611cf8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b756e4dc-0aab-4091-8012-c4c644c233ba
        userCondition: null
fields:
  63092641-8191-4272-9d2b-870c0e7aa674: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'To edit the alt text, credit the photographer or edit the image, double click on it.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
