field: 0f821582-b0f9-4517-9422-53b6ce1325ac # Content Matrix
fieldLayouts:
  e3f661b6-3fa5-4bd5-9e9f-5eba75070c75:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56371b8f-300e-443b-b33a-c161122a03e2 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20f3c66c-054c-45b8-8920-00d26e765d35
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1af14c33-3650-456a-964e-6c3b36535689 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2976cf18-c153-48b8-b0cf-9f5906217ed9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22495aea-1ee3-41b8-9e04-206260f630a6 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6c22685-9998-4d42-9651-d710081a2e28
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f6f761d-ebbd-4b44-9027-2e5a774d10d0
        userCondition: null
fields:
  1af14c33-3650-456a-964e-6c3b36535689: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  22495aea-1ee3-41b8-9e04-206260f630a6: # Layout
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'Select the layout for this block'
    name: Layout
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Text / Image'
            -
              - value
              - textImage
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Image / Text'
            -
              - value
              - imageText
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  56371b8f-300e-443b-b33a-c161122a03e2: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textImage
name: 'Text + Image'
sortOrder: 4
