fieldLayouts:
  7a95ff23-bc4c-48bc-8e7e-1cc87c6654ee:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 2fc9507b-ac5e-436f-a5b1-8cab7ec4c969
            warning: null
            width: 100
        name: Content
        uid: 2fe7003a-f825-4290-bd45-b9ff6042eead
handle: keywords
name: Keywords
