fieldLayouts:
  414f5591-4c22-4b53-92b7-a0c508eb4a87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5c776efe-39b9-4d67-a441-a5ba8d9a19b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f984d80e-8891-459f-aea7-a7d6df67e010 # Page Target
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 777d7ca0-36c1-4432-9788-a7e1f1272065
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9848f732-a6eb-413f-993f-c47d65389512
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: b5705248-eb29-4714-bfa8-40499641ca95 # Menu - Header
sortOrder: 1
titleFormat: '{pageTarget.text}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
