allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  1525beae-1aa5-4f28-8e58-76fac2482471:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-10T11:06:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d28aee79-49cb-4af8-9cf9-8e5d5caf9ca3 # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6b68b13-0cf7-4c88-8864-2818f2db256c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-10T11:06:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1edd02fb-b01b-4fc9-90fb-0b111094ab5f # Form
            handle: null
            instructions: null
            label: Form
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed0f1f68-a013-4497-bf6c-267b5bdbcebf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f6d65961-c80a-4896-972d-9ec8dd995341
        userCondition: null
    thumbFieldKey: null
handle: form
hasTitleField: false
icon: file-pen
name: 'Block: Form'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
