color: null
fieldLayouts:
  1525beae-1aa5-4f28-8e58-76fac2482471:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f3b2aa5-6021-4e2d-84ac-5fca5bce27f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04d471b6-495e-4558-b583-c7c366635c98
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44b127c2-42f2-40ec-9f23-8219ed214d34
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1edd02fb-b01b-4fc9-90fb-0b111094ab5f
            handle: null
            includeInCards: false
            instructions: null
            label: Form
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed0f1f68-a013-4497-bf6c-267b5bdbcebf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f6d65961-c80a-4896-972d-9ec8dd995341
        userCondition: null
handle: form
hasTitleField: false
icon: ''
name: 'Block: Form'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
