fieldLayouts:
  d4f767be-c51f-4279-9f34-31f6574ac54c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 460bbc59-2a42-4a11-9d19-64b16596c5ba # Page Target
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Menu Item'
        sortOrder: 1
handle: menuItem
hasTitleField: false
name: 'Menu Item'
section: 272b080b-33ab-4e23-ab30-47ae14667b77 # Menu - Header
sortOrder: 1
titleFormat: '{pageTarget.text}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
