color: null
fieldLayouts:
  cc0dc321-be99-46d4-91f9-d533b05ef040:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-10T11:06:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1ef86e1e-e03c-40d3-94b8-2db58896ec0d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-10T11:06:02+00:00'
            elementCondition: null
            fieldUid: 0f821582-b0f9-4517-9422-53b6ce1325ac # Content Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff008eeb-693e-49d2-b011-73c36e45f793
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4db9a164-d1b3-4b72-b7ce-8c7b309bb0b0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-10T11:06:02+00:00'
            elementCondition: null
            fieldUid: d2c56410-5eb0-4ddf-a3dc-00036cbef8c0 # Meta Data
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33ec22f4-1108-4a8a-81ff-279497766cc8
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4fc8a576-820b-452e-9fc4-69fcd6698bc9
        userCondition: null
handle: page
hasTitleField: true
icon: null
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
