fieldLayouts:
  cc0dc321-be99-46d4-91f9-d533b05ef040:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1ef86e1e-e03c-40d3-94b8-2db58896ec0d
            warning: null
            width: 100
          -
            fieldUid: 0f821582-b0f9-4517-9422-53b6ce1325ac # Content Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff008eeb-693e-49d2-b011-73c36e45f793
            warning: null
            width: 100
        name: Content
        uid: 4db9a164-d1b3-4b72-b7ce-8c7b309bb0b0
      -
        elements:
          -
            fieldUid: d2c56410-5eb0-4ddf-a3dc-00036cbef8c0 # Meta Data
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33ec22f4-1108-4a8a-81ff-279497766cc8
            warning: null
            width: 100
        name: SEO
        uid: 4fc8a576-820b-452e-9fc4-69fcd6698bc9
handle: page
hasTitleField: true
name: Page
section: b7de99ca-42a6-47d5-a87c-7543f84e639c # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
