color: null
fieldLayouts:
  e3f661b6-3fa5-4bd5-9e9f-5eba75070c75:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d367c739-e20b-4b3a-a74a-46b4946bb9b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22495aea-1ee3-41b8-9e04-206260f630a6 # Layout
            handle: null
            includeInCards: true
            instructions: null
            label: Layout
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6c22685-9998-4d42-9651-d710081a2e28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d28aee79-49cb-4af8-9cf9-8e5d5caf9ca3 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc55bf83-5c20-47b4-b6a2-c4849bb51c8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63092641-8191-4272-9d2b-870c0e7aa674 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79f50c57-2aba-4535-a538-2eea9273e7e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d02b3f6-61ac-492a-9508-03dabf8c93e2 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eb9d206-7b8f-4c79-a624-125dbf3e00a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f6f761d-ebbd-4b44-9027-2e5a774d10d0
        userCondition: null
handle: textImage
hasTitleField: false
icon: ''
name: 'Block: Text + Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
