color: null
fieldLayouts:
  e3f661b6-3fa5-4bd5-9e9f-5eba75070c75:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d367c739-e20b-4b3a-a74a-46b4946bb9b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22495aea-1ee3-41b8-9e04-206260f630a6
            handle: null
            includeInCards: true
            instructions: null
            label: Layout
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6c22685-9998-4d42-9651-d710081a2e28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56371b8f-300e-443b-b33a-c161122a03e2
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20f3c66c-054c-45b8-8920-00d26e765d35
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1af14c33-3650-456a-964e-6c3b36535689
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2976cf18-c153-48b8-b0cf-9f5906217ed9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28acf5ce-1530-440f-a016-28e61b84f780
            handle: buttons
            includeInCards: false
            instructions: null
            label: Buttons
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d0701a4-4d35-4d63-bac2-d0051632d57c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f6f761d-ebbd-4b44-9027-2e5a774d10d0
        userCondition: null
handle: textImage
hasTitleField: false
icon: ''
name: 'Block: Text + Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
