color: null
fieldLayouts:
  085ac208-518d-4e2b-9d15-bf3a68810673:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ec2999c-634f-44b8-b869-7313a962eca6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41e0b3cc-ad7b-47c5-a503-a5dac4e24af0
            handle: null
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7558004-ab81-4452-87ee-2cf8cfff52c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d02b3f6-61ac-492a-9508-03dabf8c93e2
            handle: null
            includeInCards: false
            instructions: null
            label: Buttons
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2c5d143-cc81-4b48-b23b-5f560d23ab72
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9fc7f30a-ba9d-47d1-aab2-016a6faf3eee
        userCondition: null
handle: text
hasTitleField: false
icon: ''
name: 'Block: Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
