color: null
fieldLayouts:
  085ac208-518d-4e2b-9d15-bf3a68810673:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-10T11:06:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ec2999c-634f-44b8-b869-7313a962eca6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-10T11:06:02+00:00'
            elementCondition: null
            fieldUid: d28aee79-49cb-4af8-9cf9-8e5d5caf9ca3 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d33759a2-be29-40af-8f12-79a2c0fdc469
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-10T11:06:02+00:00'
            elementCondition: null
            fieldUid: 7d02b3f6-61ac-492a-9508-03dabf8c93e2
            handle: null
            includeInCards: false
            instructions: null
            label: Buttons
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2c5d143-cc81-4b48-b23b-5f560d23ab72
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9fc7f30a-ba9d-47d1-aab2-016a6faf3eee
        userCondition: null
handle: text
hasTitleField: false
icon: null
name: 'Block: Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
