color: null
fieldLayouts:
  4287605c-0ca2-49db-8eae-1d0656fb9582:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ccce90c5-bfcb-4a76-9a0b-dc2fb90ff3d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d28aee79-49cb-4af8-9cf9-8e5d5caf9ca3 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b10cc38e-b232-49eb-a601-f11507c08169
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1b16bb99-ac4b-4bc8-85f8-71966c72102e # Video Embed Code
            handle: null
            includeInCards: false
            instructions: null
            label: 'Video Embed Code'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff245f38-7b68-4deb-8ca0-d978e23565ff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 73d84bf2-af78-4597-a4ce-06fc4d4ca5a2
        userCondition: null
handle: video
hasTitleField: false
icon: ''
name: 'Block: Video'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
