allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  4287605c-0ca2-49db-8eae-1d0656fb9582:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-10T11:06:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d28aee79-49cb-4af8-9cf9-8e5d5caf9ca3 # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b10cc38e-b232-49eb-a601-f11507c08169
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-10T11:06:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1b16bb99-ac4b-4bc8-85f8-71966c72102e # Video Embed Code
            handle: null
            instructions: null
            label: 'Video Embed Code'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff245f38-7b68-4deb-8ca0-d978e23565ff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 73d84bf2-af78-4597-a4ce-06fc4d4ca5a2
        userCondition: null
    thumbFieldKey: null
handle: video
hasTitleField: false
icon: youtube
name: 'Block: Video'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
