headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
listPlugin: DocumentList
name: Standard
options:
  alignment:
    options:
      - left
      - center
toolbar:
  - sourceEditing
  - heading
  - '|'
  - bold
  - italic
  - link
  - alignment
  - bulletedList
  - numberedList
  - horizontalLine
  - insertTable
  - blockQuote
