headingLevels:
  - 2
  - 3
  - 4
listPlugin: DocumentList
name: Standard
options:
  alignment:
    options:
      - left
      - center
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
  - alignment
  - bulletedList
  - numberedList
  - horizontalLine
