css: ".ck .table {\r\n  width: 100%;\r\n}"
headingLevels:
  - 2
  - 3
  - 4
listPlugin: DocumentList
name: Standard
options:
  alignment:
    options:
      - left
      - center
toolbar:
  - sourceEditing
  - heading
  - '|'
  - bold
  - italic
  - link
  - alignment
  - bulletedList
  - numberedList
  - horizontalLine
  - insertTable
  - blockQuote
