headingLevels: false
name: Simple
options:
  link:
    decorators:
      isExternal:
        attributes:
          target: _blank
        label: 'Open in a new tab'
        mode: manual
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
