fieldLayouts:
  c1b71ef2-a350-46de-9849-95952c39ea5a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0e0eaf98-8206-41ee-aa20-b8d1c3bdf719
            warning: null
            width: 100
          -
            fieldUid: 87e23d73-06c0-42d0-859f-8ae90ac61e88 # Asset - Alt Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43c88f37-59ea-4796-b9b8-6912e8dabb04
            warning: null
            width: 100
          -
            fieldUid: d55b8864-3ed0-46c2-9796-902e5fdafb40 # Asset - Photo Credit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7170a90-7cf9-410b-ac6d-eb0a50e97713
            warning: null
            width: 100
        name: Asset
        uid: ae73c5e3-e8cb-47f9-b5e0-f87cc9ff0715
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
