fieldLayouts:
  73d01e66-0e22-449e-913f-cf6508764087:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 30f21b12-f039-4a2f-abab-4ed01742a218
            warning: null
            width: 100
        name: Content
        uid: 1258e9d0-2fed-407e-bd49-a654848e83c8
fs: seo
handle: seo
name: SEO
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
