fieldLayouts:
  73d01e66-0e22-449e-913f-cf6508764087:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 30f21b12-f039-4a2f-abab-4ed01742a218
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 44d68d8b-d55a-4d03-8e3e-ed4b3b742685
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d55b8864-3ed0-46c2-9796-902e5fdafb40 # Asset - Photo Credit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41b03db5-da7e-43b3-b739-41e6e8bd472d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1258e9d0-2fed-407e-bd49-a654848e83c8
        userCondition: null
fs: seo
handle: seo
name: SEO
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
