fieldLayouts:
  9b51f130-54e3-4503-9a73-9527b1f8fab1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 608369a3-c6c5-45ee-a427-9a8f8368b16b
            warning: null
            width: 100
        name: Content
        uid: 02ef9582-02f8-4e39-8b57-33d39e8dadaf
fs: userPhotos
handle: userPhotos
name: 'User Photos'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
