columnSuffix: null
handle: alertBarText
instructions: null
name: 'Alert Bar - Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: dbe4010f-eb87-4e95-a69c-087821b73327 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
