columnSuffix: null
contentColumnType: string(600)
fieldGroup: 5e6ccb6c-d6eb-446b-8ce9-aa8bb3fcf575 # Assets
handle: assetAltText
instructions: 'Enter alternative text if the image can''t be seen - used for SEO and accessibility. This will default to the asset title if nothing is entered'
name: 'Asset - Alt Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 150
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
