columnSuffix: null
handle: endDate
instructions: 'When the alert should stop showing'
name: 'Alert Bar - Alert - End Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 60
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
