columnSuffix: null
handle: form
instructions: 'Select a form to include. Forms can be created and edited from the **Forms** option in the sidebar on the left'
name: Form
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: verbb\formie\fields\Forms
