columnSuffix: null
contentColumnType: text
handle: metaData
instructions: 'This field allows you to override the SEO settings for this entry'
name: 'Meta Data'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
    - robots
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
