columnSuffix: null
handle: startDate
instructions: 'When the alert should start showing'
name: 'Alert Bar - Alert - Start Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 60
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
