columnSuffix: null
handle: text5
instructions: 'The text of the alert bar'
name: 'Alert Bar - Alert - Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: dbe4010f-eb87-4e95-a69c-087821b73327 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
