columnSuffix: null
contentColumnType: text
fieldGroup: 549503cf-e3fa-4dda-89d3-1f2e17735cb3 # Globals
handle: text404
instructions: 'This appears on the 404 page, which happens when a page the user is trying to view doesn''t exist'
name: '404 Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 3c62ae9b-e6d3-4100-a0d1-1c5abab96be2 # Standard
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
