dateModified: 1739270697
elementSources:
  craft\elements\Asset:
    -
      heading: Images
      type: heading
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - imageSize
        - link
      type: native
    -
      heading: Documents
      type: heading
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      heading: System
      type: heading
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:6b6bbbe4-2628-4f6e-9c4c-f5be79037ddd' # SEO
      tableAttributes:
        - filename
        - size
        - dateModified
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:a5e83d06-7ec6-4498-bb8d-53746387cc28' # User Photos
      tableAttributes:
        - filename
        - size
        - dateModified
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'folder:3b990b82-599f-4fb4-8d57-f1a236ee7971'
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
  craft\elements\Entry:
    -
      heading: 'Site Pages'
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
      tableAttributes:
        - type
        - dateUpdated
        - uri
      type: native
    -
      heading: Navigation
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
      tableAttributes: '-'
      type: native
    -
      heading: Everything
      type: heading
    -
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - dateUpdated
      type: native
  craft\elements\User:
    -
      heading: Users
      type: heading
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: 'group:4e8528d9-c0c1-45d4-affa-da3b37001b13' # Site Admin
      tableAttributes:
        - email
        - lastLoginDate
      type: native
    -
      heading: Developers
      type: heading
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: admins
      tableAttributes:
        - email
        - lastLoginDate
      type: native
    -
      heading: Everyone
      type: heading
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: '*'
      tableAttributes:
        - email
        - lastLoginDate
      type: native
    -
      heading: Other
      type: heading
    -
      defaultSort:
        - email
        - asc
      disabled: true
      key: credentialed
      tableAttributes:
        - email
        - lastLoginDate
      type: native
    -
      defaultSort:
        - email
        - asc
      disabled: true
      key: inactive
      tableAttributes:
        - email
        - lastLoginDate
      type: native
email:
  fromEmail: $EMAIL_SYSTEM_ADDRESS
  fromName: $EMAIL_SENDER
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: $EMAIL_ENCRYPTION
    host: $EMAIL_HOST
    password: $EMAIL_PASSWORD
    port: $EMAIL_PORT
    timeout: '30'
    useAuthentication: $EMAIL_AUTH
    username: $EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@webroot/uploads/files'
    type: craft\fs\Local
    url: '@web/uploads/files'
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
  seo:
    hasUrls: true
    name: SEO
    settings:
      path: '@webroot/uploads/seo'
    type: craft\fs\Local
    url: '@web/uploads/seo'
  userPhotos:
    hasUrls: true
    name: 'User Photos'
    settings:
      path: '@webroot/uploads/users'
    type: craft\fs\Local
    url: '@web/uploads/users'
meta:
  __names__:
    0defd9a0-66bd-4509-aa52-57274feb18d7: '404 Heading' # 404 Heading
    0f57cf4e-d77d-4b47-bc2c-46a7aeb51e24: New # New
    0f821582-b0f9-4517-9422-53b6ce1325ac: 'Content Matrix' # Content Matrix
    1b16bb99-ac4b-4bc8-85f8-71966c72102e: 'Video Embed Code' # Video Embed Code
    1edd02fb-b01b-4fc9-90fb-0b111094ab5f: Form # Form
    2ed25488-1bf1-4e97-b75b-0985a25733f9: 'Matrix: Button' # Matrix: Button
    3c62ae9b-e6d3-4100-a0d1-1c5abab96be2: Standard # Standard
    4e8528d9-c0c1-45d4-affa-da3b37001b13: 'Site Admin' # Site Admin
    5afb69df-76c7-42e3-9af4-bc31faefa3d5: 'Alert Bar - End Date' # Alert Bar - End Date
    6b6bbbe4-2628-4f6e-9c4c-f5be79037ddd: SEO # SEO
    08d0227a-6f2b-43f5-a49d-c43fc178a53a: Files # Files
    17c63dc5-a8a5-4077-84e6-6f5d5baa1e46: 'Alert Bar - Start Date' # Alert Bar - Start Date
    30ba6aa9-32c2-4356-8811-0ba5fe3b2171: 'Block: Image' # Block: Image
    33af4157-ab80-44a3-b036-006aac36eacf: Images # Images
    60b2f9cd-8e83-49e0-921e-f6d0b325e69d: 'Alert Bar - Text' # Alert Bar - Text
    234a402e-c9d9-4986-a8da-cae7de748a32: 'Block: Text' # Block: Text
    274b53b7-b114-412d-8a2b-b9eae52f9822: 'Page > Content' # Page > Content
    414e3fb0-5309-47af-8bcc-920b35c18875: 'Menu Item' # Menu Item
    0468bb2b-6b23-493c-9867-c8e7fb7f4431: '404 Text' # 404 Text
    669efec2-e57d-4d6f-9adc-4e4cf69972d0: Alert # Alert
    6975e64f-9cc5-4116-bee9-1458fdfedaeb: 'Public Schema' # Public Schema
    22495aea-1ee3-41b8-9e04-206260f630a6: Layout # Layout
    138367f7-dc97-47dc-b20f-5db11ef457b3: 'Block: Text + Image' # Block: Text + Image
    63092641-8191-4272-9d2b-870c0e7aa674: Image # Image
    93796209-b311-4bfa-8cd4-fd9b8ca6d012: '404 Error' # 404 Error
    a5e83d06-7ec6-4498-bb8d-53746387cc28: 'User Photos' # User Photos
    b1b58943-2b7b-479b-8caf-59ecaad36651: Default # Default
    b7de99ca-42a6-47d5-a87c-7543f84e639c: Pages # Pages
    b5705248-eb29-4714-bfa8-40499641ca95: 'Menu - Header' # Menu - Header
    c615a9c4-62f7-45b2-b1fd-ca823af0de54: Buttons # Buttons
    c2434455-665e-4005-81d8-6df1bc63b014: $SYSTEM_NAME # $SYSTEM_NAME
    cbd7becc-06f1-4c4c-b953-45081affffaf: 'Alert Bar' # Alert Bar
    cc626e87-09aa-4a14-80e4-d44dbd87d144: 'Block: Video' # Block: Video
    d1c70998-f4bf-4681-922e-921e2a526697: 'Contact Form' # Contact Form
    d2c56410-5eb0-4ddf-a3dc-00036cbef8c0: 'Meta Data' # Meta Data
    d28aee79-49cb-4af8-9cf9-8e5d5caf9ca3: Text # Text
    e72fcb39-677a-4ffd-ae05-3064e47f7215: 'Block: Form' # Block: Form
    f386df65-5754-4161-9cbb-ffc7042904cb: Button # Button
plugins:
  admin-bar:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
    settings:
      customCss: "admin-bar {\r\n    position: fixed;\r\n    top: auto;\r\n    bottom: 0;\r\n    z-index: 999;\r\n}\r\nbody {\r\n    padding-bottom: 43px;\r\n}"
      customLinks:
        -
          __assoc__:
            -
              - linkLabel
              - ''
            -
              - linkUrl
              - ''
            -
              - adminOnly
              - ''
      displayDashboardLink: false
      displayDefaultEditSection: false
      displayGreeting: true
      displayGuideLink: true
      displayLogout: true
      displaySettingsLink: false
      displayUtilitiesLink: true
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_FORMIE
    schemaVersion: 3.4.8
    settings:
      ajaxTimeout: 10
      alertEmails: null
      captchas:
        __assoc__:
          -
            - recaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Recaptcha
                -
                  - enabled
                  - $FORMIE_CAPTCHA_RECAPTCHA
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - recaptcha
                      -
                        - type
                        - v3
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - badge
                        - bottomright
                      -
                        - language
                        - en
                      -
                        - minScore
                        - 0.5
                      -
                        - scriptLoadingMethod
                        - asyncDefer
          -
            - hcaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Hcaptcha
                -
                  - enabled
                  - $FORMIE_CAPTCHA_HCAPTCHA
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - hcaptcha
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - language
                        - en
                      -
                        - minScore
                        - 0.5
                      -
                        - scriptLoadingMethod
                        - asyncDefer
          -
            - duplicate
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Duplicate
                -
                  - enabled
                  - $FORMIE_CAPTCHA_DUPLICATE
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - duplicate
          -
            - honeypot
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Honeypot
                -
                  - enabled
                  - $FORMIE_CAPTCHA_HONEYPOT
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - honeypot
          -
            - javascript
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Javascript
                -
                  - enabled
                  - $FORMIE_CAPTCHA_JAVASCRIPT
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - javascript
      defaultDateDisplayType: calendar
      defaultDateTime: null
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: verbb\formie\positions\AboveInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: forms
      emptyValuePlaceholder: 'No response.'
      enableBackSubmission: true
      enableCsrfValidationForGuests: true
      enableLargeFieldStorage: false
      enableUnloadWarning: false
      includeDraftElementUsage: false
      includeRevisionElementUsage: false
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      pluginName: Forms
      queuePriority: null
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamEmailNotifications: false
      spamKeywords: ''
      spamLimit: 500
      useQueueForIntegrations: false
      useQueueForNotifications: false
      validateCustomTemplates: true
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_RETOUR
    schemaVersion: 3.0.12
  seomatic:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_SEOMATIC
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: false
      submitSitemaps: true
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: $SYSTEM_STATUS
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: Europe/London
