dateModified: 1643801511
email:
  fromEmail: $EMAIL_SYSTEM_ADDRESS
  fromName: $EMAIL_SENDER
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: $EMAIL_HOST
    password: $EMAIL_PASSWORD
    port: $EMAIL_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    0defd9a0-66bd-4509-aa52-57274feb18d7: '404 Heading' # 404 Heading
    0f821582-b0f9-4517-9422-53b6ce1325ac: 'Content Matrix' # Content Matrix
    1af14c33-3650-456a-964e-6c3b36535689: Image # Image
    1b16bb99-ac4b-4bc8-85f8-71966c72102e: 'Video Embed Code' # Video Embed Code
    1edd02fb-b01b-4fc9-90fb-0b111094ab5f: Form # Form
    04d471b6-495e-4558-b583-c7c366635c98: Text # Text
    4e8528d9-c0c1-45d4-affa-da3b37001b13: 'Site Admin' # Site Admin
    5afb69df-76c7-42e3-9af4-bc31faefa3d5: 'End Date' # End Date
    5e6ccb6c-d6eb-446b-8ce9-aa8bb3fcf575: Assets # Assets
    6b6bbbe4-2628-4f6e-9c4c-f5be79037ddd: SEO # SEO
    6d55684e-15e8-4a1c-886b-c0a88a73fa37: 'Menu - Footer' # Menu - Footer
    08d0227a-6f2b-43f5-a49d-c43fc178a53a: Files # Files
    9c3f09c1-dd31-4a39-8fd5-a5c28c95ad98: Button # Button
    17b216fe-faa2-4aed-b927-03b84406a9fc: Text # Text
    17c63dc5-a8a5-4077-84e6-6f5d5baa1e46: 'Start Date' # Start Date
    24bf3782-f6ee-4ede-be36-2374c6331dfa: Caption # Caption
    33af4157-ab80-44a3-b036-006aac36eacf: Images # Images
    41e0b3cc-ad7b-47c5-a503-a5dac4e24af0: Columns # Columns
    60b2f9cd-8e83-49e0-921e-f6d0b325e69d: Text # Text
    76dd902c-6643-4db8-a27c-e2e1b3142fb0: Text # Text
    87b794fa-7c3f-43aa-818e-433587a2c54d: 'Menu Item' # Menu Item
    87e23d73-06c0-42d0-859f-8ae90ac61e88: 'Asset - Alt Text' # Asset - Alt Text
    234a402e-c9d9-4986-a8da-cae7de748a32: Text # Text
    272b080b-33ab-4e23-ab30-47ae14667b77: 'Menu - Header' # Menu - Header
    274b53b7-b114-412d-8a2b-b9eae52f9822: Page # Page
    460bbc59-2a42-4a11-9d19-64b16596c5ba: 'Page Target' # Page Target
    0468bb2b-6b23-493c-9867-c8e7fb7f4431: '404 Text' # 404 Text
    631f7883-af4d-4cd9-8811-62ba70b2ae77: Navigation # Navigation
    669efec2-e57d-4d6f-9adc-4e4cf69972d0: Alert # Alert
    929a1c10-6bba-4747-a328-fe6e9cbd4bad: Text # Text
    6975e64f-9cc5-4116-bee9-1458fdfedaeb: 'Public Schema' # Public Schema
    22495aea-1ee3-41b8-9e04-206260f630a6: Layout # Layout
    56371b8f-300e-443b-b33a-c161122a03e2: Text # Text
    67840ae5-eb64-4d49-a47f-3bdf0458a447: Content # Content
    138367f7-dc97-47dc-b20f-5db11ef457b3: 'Text + Image' # Text + Image
    549503cf-e3fa-4dda-89d3-1f2e17735cb3: Globals # Globals
    93796209-b311-4bfa-8cd4-fd9b8ca6d012: '404 Error' # 404 Error
    a4d47a90-98af-4c19-9e35-65535ddaebb3: SEO # SEO
    a5e83d06-7ec6-4498-bb8d-53746387cc28: 'User Photos' # User Photos
    a26ace53-7398-4726-bd29-3e90e8fb40f0: 'Menu Item' # Menu Item
    a7056238-d6aa-44ea-b45a-c079ea6053e7: Button # Button
    ad52075d-406a-4f0b-a05f-4605f97944e7: 'Video Intro' # Video Intro
    b1b58943-2b7b-479b-8caf-59ecaad36651: Default # Default
    b7de99ca-42a6-47d5-a87c-7543f84e639c: Pages # Pages
    c4fb0464-3077-45aa-9c64-7e0015f54677: 'Alert Bar' # Alert Bar
    c2434455-665e-4005-81d8-6df1bc63b014: 'Tailwind Mix' # Tailwind Mix
    cbd7becc-06f1-4c4c-b953-45081affffaf: 'Alert Bar' # Alert Bar
    cc626e87-09aa-4a14-80e4-d44dbd87d144: Video # Video
    d2c56410-5eb0-4ddf-a3dc-00036cbef8c0: 'Meta Data' # Meta Data
    d738c390-8d55-4719-a22c-15c3927411a2: Default # Default
    e48df75a-1eb4-4f41-ae54-3712790af8ce: Keywords # Keywords
    e72fcb39-677a-4ffd-ae05-3064e47f7215: Form # Form
    eac1b272-bafe-43df-a0f6-fa48ac37a670: Buttons # Buttons
    f873c1df-d476-417a-b57c-26e7c609c183: 'Image Size' # Image Size
    fa97b4d1-33c1-4819-a6c4-c441f301ec4f: Image # Image
    ff17f800-7774-4a64-848b-f3abe5d77ee4: Heading # Heading
plugins:
  admin-bar:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: lite
    enabled: true
    licenseKey: GKHZ54GBHSA7RFB48772UGDH
    schemaVersion: 3.5.1
    settings:
      ajaxByDefault: '1'
      alertNotificationRecipients: null
      autoScroll: '1'
      autoScrollToErrors: '1'
      badgeType: errors
      blockedEmails: ''
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: ''
      blockedKeywords: ''
      blockedKeywordsError: 'Invalid Entry Data'
      clientDigestFrequency: 1
      clientDigestRecipients: null
      customErrorMessage: ''
      customHoneypotName: ''
      defaultTemplates: '1'
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: null
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: ''
      footerScripts: false
      formFieldShowOnlyAllowedForms: ''
      formSubmitDisable: '1'
      formSubmitExpiration: ''
      formTemplateDirectory: null
      formattingTemplate: tailwind.html
      freeformHoneypot: '1'
      freeformHoneypotEnhancement: '1'
      hideBannerDemo: '1'
      hideBannerOldFreeform: false
      minimumSubmitTime: ''
      pluginName: null
      purgableSpamAgeInDays: '14'
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: '1'
      removeNewlines: ''
      renderFormHtmlInCpViews: '1'
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionContext: payload
      sessionContextCount: '100'
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: '180'
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: ''
      showErrorsForBlockedKeywords: ''
      showTutorial: '1'
      spamFolderEnabled: '1'
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: ''
      submissionThrottlingTimeFrame: m
      twigInHtml: '1'
      twigInHtmlIsolatedMode: '1'
      updateSearchIndexes: '1'
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: dist
      publicPath: public
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: IBI1JHBIMM8INDF9M20L80MA
    schemaVersion: 3.0.11
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: false
      submitSitemaps: true
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  sherlock:
    edition: lite
    enabled: true
    schemaVersion: 3.1.3
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Boilerplate Tailwind'
  retryDuration: null
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
