changedFieldIndicator: 1015807478
field: 41e0b3cc-ad7b-47c5-a503-a5dac4e24af0 # Text
fieldLayouts:
  618a3532-44ec-4808-9f99-6efa2826ae36:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 76dd902c-6643-4db8-a27c-e2e1b3142fb0 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59e7c32c-2897-4fe0-add8-d62ff48f0539
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f07b63c9-5f4a-489b-b7dd-ee01dc2e2dea
        userCondition: null
fields:
  76dd902c-6643-4db8-a27c-e2e1b3142fb0: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
