fieldLayouts:
  0647ea85-6ad1-48ad-8d63-5524839e47c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0defd9a0-66bd-4509-aa52-57274feb18d7 # 404 Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a52d592-806c-4803-b0e3-343287617c8f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0468bb2b-6b23-493c-9867-c8e7fb7f4431 # 404 Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a0f2b63-1bc1-43fd-9f64-17565bbe0b19
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 772352b9-f4fd-4f06-b4dd-2ff5a7c41ee9
        userCondition: null
handle: error404
name: '404 Error'
sortOrder: 2
