description: 'This group of users administers the content for the website'
handle: siteAdmin
name: 'Site Admin'
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-freeform
  - accessplugin-seomatic
  - accesssitewhensystemisoff
  - 'assignusergroup:4e8528d9-c0c1-45d4-affa-da3b37001b13' # Site Admin
  - 'createentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'createentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'createentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'deleteentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'deleteentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'deleteentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'deletepeerentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'deletepeerentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'deletepeerentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'deletepeerentrydrafts:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'deletepeerentrydrafts:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'deletepeerentrydrafts:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - deleteusers
  - 'editglobalset:93796209-b311-4bfa-8cd4-fd9b8ca6d012' # 404 Error
  - 'editglobalset:cbd7becc-06f1-4c4c-b953-45081affffaf' # Alert Bar
  - editusers
  - freeform-access-quick-export
  - freeform-dashboardaccess
  - freeform-fieldsaccess
  - freeform-fieldsmanage
  - freeform-formsaccess
  - freeform-formscreate
  - freeform-formsdelete
  - freeform-formsmanage
  - 'freeform-formsmanage:1'
  - freeform-formsmanageindividual
  - freeform-notificationsaccess
  - freeform-notificationsmanage
  - freeform-pro-exportprofilesaccess
  - freeform-pro-exportprofilesmanage
  - freeform-resources
  - freeform-settingsaccess
  - freeform-submissionsaccess
  - freeform-submissionsmanage
  - 'freeform-submissionsmanage:1'
  - freeform-submissionsmanageindividual
  - freeform-submissionsread
  - 'freeform-submissionsread:1'
  - freeform-submissionsreadindividual
  - moderateusers
  - registerusers
  - 'seomatic:dashboard'
  - 'seomatic:global-meta'
  - 'seomatic:global-meta:ads'
  - 'seomatic:global-meta:facebook'
  - 'seomatic:global-meta:general'
  - 'seomatic:global-meta:humans'
  - 'seomatic:global-meta:robots'
  - 'seomatic:global-meta:security'
  - 'seomatic:global-meta:twitter'
  - 'seomatic:site-settings'
  - 'seomatic:site-settings:creator'
  - 'seomatic:site-settings:identity'
  - 'seomatic:site-settings:miscellaneous'
  - 'seomatic:site-settings:sitemap'
  - 'seomatic:site-settings:social'
  - 'viewassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'saveassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'deleteassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'replacefiles:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'editimages:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'viewpeerassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'savepeerassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'replacepeerfiles:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'deletepeerassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'editpeerimages:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'createfolders:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'viewassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'saveassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'deleteassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'replacefiles:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'editimages:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'viewpeerassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'savepeerassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'replacepeerfiles:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'deletepeerassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'editpeerimages:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'createfolders:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'viewentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'saveentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'viewpeerentrydrafts:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'savepeerentrydrafts:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'viewpeerentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'savepeerentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'viewentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'saveentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'viewpeerentrydrafts:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'savepeerentrydrafts:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'viewpeerentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'savepeerentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'viewentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'saveentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'viewpeerentrydrafts:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'savepeerentrydrafts:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'viewpeerentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'savepeerentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
