description: 'This group of users administers the content for the website'
handle: siteAdmin
name: 'Site Admin'
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accesssitewhensystemisoff
  - 'assignusergroup:4e8528d9-c0c1-45d4-affa-da3b37001b13' # Site Admin
  - 'createentries:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'createentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'createfolders:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'createfolders:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'deleteassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'deleteassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'deleteentries:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'deleteentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'deletepeerassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'deletepeerassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'deletepeerentries:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'deletepeerentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'deletepeerentrydrafts:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'deletepeerentrydrafts:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - deleteusers
  - 'editglobalset:93796209-b311-4bfa-8cd4-fd9b8ca6d012' # 404 Error
  - 'editglobalset:cbd7becc-06f1-4c4c-b953-45081affffaf' # Alert Bar
  - 'editimages:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'editimages:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'editpeerimages:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'editpeerimages:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - editusers
  - formie-createforms
  - formie-createsubmissions
  - formie-deleteforms
  - formie-editforms
  - formie-editsubmissions
  - formie-manageformappearance
  - formie-manageformbehavior
  - formie-manageformintegrations
  - formie-manageformsettings
  - formie-managenotifications
  - formie-managenotificationsadvanced
  - formie-managenotificationstemplates
  - 'formie-managesubmission:9824926f-7516-4539-b68c-ab0bd3e39034'
  - formie-viewforms
  - formie-viewsentnotifications
  - formie-viewsubmissions
  - moderateusers
  - registerusers
  - 'replacefiles:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'replacefiles:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'replacepeerfiles:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'replacepeerfiles:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'saveassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'saveassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'saveentries:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'saveentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'savepeerassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'savepeerassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'savepeerentries:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'savepeerentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'savepeerentrydrafts:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'savepeerentrydrafts:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'utility:php-info'
  - 'utility:system-report'
  - 'utility:updates'
  - 'viewassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'viewassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'viewentries:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'viewentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'viewpeerassets:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'viewpeerassets:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'viewpeerentries:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'viewpeerentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'viewpeerentrydrafts:b5705248-eb29-4714-bfa8-40499641ca95' # Menu - Header
  - 'viewpeerentrydrafts:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
