description: 'This group of users administers the content for the website'
handle: siteAdmin
name: 'Site Admin'
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-freeform
  - accessplugin-seomatic
  - accesssitewhensystemisoff
  - 'assignusergroup:4e8528d9-c0c1-45d4-affa-da3b37001b13' # Site Admin
  - assignusergroups
  - 'createentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'createentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'createentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'createfoldersinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'createfoldersinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'deleteentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'deleteentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'deleteentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'deletefilesandfoldersinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'deletefilesandfoldersinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'deletepeerentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'deletepeerentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'deletepeerentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'deletepeerentrydrafts:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'deletepeerentrydrafts:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'deletepeerentrydrafts:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'deletepeerfilesinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'deletepeerfilesinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - deleteusers
  - 'editentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'editentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'editentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'editglobalset:93796209-b311-4bfa-8cd4-fd9b8ca6d012' # 404 Error
  - 'editglobalset:cbd7becc-06f1-4c4c-b953-45081affffaf' # Alert Bar
  - 'editimagesinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'editimagesinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'editpeerentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'editpeerentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'editpeerentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'editpeerentrydrafts:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'editpeerentrydrafts:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'editpeerentrydrafts:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'editpeerfilesinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'editpeerfilesinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'editpeerimagesinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'editpeerimagesinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - editusers
  - freeform-access-quick-export
  - freeform-dashboardaccess
  - freeform-fieldsaccess
  - freeform-fieldsmanage
  - freeform-formsaccess
  - freeform-formscreate
  - freeform-formsdelete
  - freeform-formsmanage
  - 'freeform-formsmanage:1'
  - freeform-formsmanageindividual
  - freeform-notificationsaccess
  - freeform-notificationsmanage
  - freeform-pro-exportprofilesaccess
  - freeform-pro-exportprofilesmanage
  - freeform-resources
  - freeform-settingsaccess
  - freeform-submissionsaccess
  - freeform-submissionsmanage
  - 'freeform-submissionsmanage:1'
  - freeform-submissionsmanageindividual
  - freeform-submissionsread
  - 'freeform-submissionsread:1'
  - freeform-submissionsreadindividual
  - moderateusers
  - 'publishentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'publishentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'publishentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'publishpeerentries:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'publishpeerentries:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'publishpeerentries:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - 'publishpeerentrydrafts:272b080b-33ab-4e23-ab30-47ae14667b77' # Menu - Header
  - 'publishpeerentrydrafts:6d55684e-15e8-4a1c-886b-c0a88a73fa37' # Menu - Footer
  - 'publishpeerentrydrafts:b7de99ca-42a6-47d5-a87c-7543f84e639c' # Pages
  - registerusers
  - 'replacefilesinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'replacefilesinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'replacepeerfilesinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'replacepeerfilesinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'saveassetinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'saveassetinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'seomatic:dashboard'
  - 'seomatic:global-meta'
  - 'seomatic:global-meta:ads'
  - 'seomatic:global-meta:facebook'
  - 'seomatic:global-meta:general'
  - 'seomatic:global-meta:humans'
  - 'seomatic:global-meta:robots'
  - 'seomatic:global-meta:security'
  - 'seomatic:global-meta:twitter'
  - 'seomatic:site-settings'
  - 'seomatic:site-settings:creator'
  - 'seomatic:site-settings:identity'
  - 'seomatic:site-settings:miscellaneous'
  - 'seomatic:site-settings:sitemap'
  - 'seomatic:site-settings:social'
  - 'viewpeerfilesinvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'viewpeerfilesinvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
  - 'viewvolume:08d0227a-6f2b-43f5-a49d-c43fc178a53a' # Files
  - 'viewvolume:33af4157-ab80-44a3-b036-006aac36eacf' # Images
