defaultPlacement: end
enableVersioning: true
entryTypes:
  - 414e3fb0-5309-47af-8bcc-920b35c18875 # Menu Item
handle: menuHeader
name: 'Menu - Header'
propagationMethod: all
siteSettings:
  c2434455-665e-4005-81d8-6df1bc63b014: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: a5f933ad-7307-401f-aa04-bda5def8fa6e
type: structure
