defaultPlacement: end
enableVersioning: true
handle: menuHeader
name: 'Menu - Header'
propagationMethod: all
siteSettings:
  c2434455-665e-4005-81d8-6df1bc63b014: # Boilerplate
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: b7878dd1-0966-4820-9aff-7fe250f61ba0
type: structure
