defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 274b53b7-b114-412d-8a2b-b9eae52f9822 # Page > Content
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c2434455-665e-4005-81d8-6df1bc63b014: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: 234abe7d-3a21-4669-8e38-239971a35d52
type: structure
