tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-02-10T11:06:02+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 7c023846-19bd-4330-8cda-f3cc5dc77588
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-02-10T11:06:02+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: e21b4c96-7357-413e-b531-5e5a33725bf8
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-02-10T11:06:02+00:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 7adc3fa9-a090-4ad3-b9e5-5cff4b844188
        userCondition: null
        warning: null
    name: Content
    uid: bb69d4fc-8634-422b-8df4-82f747e4f3de
    userCondition: null
